- hosts: localhost
  tasks:
# ----------------------------------------------------------------------------------
# Start with a resource group so that clean up is easy. This tasks is commented out
# since you cannot create resource group in this workshop.
# ----------------------------------------------------------------------------------
#  - name: Create a resource group
#    azure_rm_resourcegroup:
#      name: myResource_group
#      location: eastus2
# ----------------------------------------------------------------------------------
# Make sure you replace myResource_group with your resource group name.
#-----------------------------------------------------------------------------------
  - name: Create a virtual network. 
    azure_rm_virtualnetwork:
      resource_group: myResource_group
      name: myVnet
      address_prefixes: "172.16.0.0/16"

# ----------------------------------------------------------------------------------
# Make sure you replace myResource_group with your resource group name.
#-----------------------------------------------------------------------------------
  - name: Create a subnet within the virtual network
    azure_rm_subnet:
        resource_group: myResource_group
        virtual_network_name: myVnet
        name: myVnetSubnet
        address_prefix_cidr:  "172.16.10.0/24"
