- name: Create a subset within the virtual network
  azure_rm_subnet:
    resource_group: "{{ myResource_group }}"
    virtual_network_name: "{{ myVnet }}"
    name: "{{ myVnetSubNet }}"
    address_prefix_cidr:  "{{ subnetAddPrefix }}"
  register: subnet
    
- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ myResource_group }}"
    allocation_method: Static
    name: "{{ myPublicIP }}"
  register: publicIP

- name: Create Network Security Group
  azure_rm_securitygroup:
    resource_group: "{{ myResource_group }}"
    name: "{{ myNetworkSecurityGroup}}"
    rules:
      - name: "Allow-{{ item.name }}"
        protocol: Tcp
        destination_port_range: "{{ item.port }}"
        access: Allow
        priority: "{{ item.priority }}"
        direction: Inbound
  loop: "{{ NSGlist }}"
  register: NSG

- name: Create virtual network interface card(NIC) with public IP
  azure_rm_networkinterface:
    resource_group: "{{ myResource_group }}"
    name: "{{ myNIC }}"
    virtual_network: "{{ myVnet }}"
    subnet: "{{ myVnetSubNet }}"
    ip_configurations:
      - name: ipconfig1
        public_ip_address_name: "{{ myPublicIP }}"
    security_group: "{{ myNetworkSecurityGroup }}"
  register: NIC
  
    

  