- hosts: localhost
  vars_files: 
    - ./vars.yml
  roles:
    - ./modules
  gather_facts: no
    
  tasks:
# ----------------------------------------------------------------------------------
# Start with a resource group so that clean up is easy. This tasks is commented out
# since you cannot create resource group in this workshop.
# ----------------------------------------------------------------------------------
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ myResource_group }}"
      location: eastus2

  - name: Create a virtual network. 
    azure_rm_virtualnetwork:
      resource_group: "{{ myResource_group }}"
      name: "{{ myVnet }}"
      address_prefixes: "172.16.0.0/16"

  - name: Create front-end subnet and NSG rules
    vars:
      myVnetSubNet: myVnetSubNet
      myPublicIP: myPublicIP
      subnetAddPrefix:  "172.16.10.0/24"
      myNetworkSecurityGroup: myNSG
      myNIC: myNIC
      NSGlist: [{ name: 'Allow-SSH', access: 'Allow', protocol: 'Tcp', direction: 'Inbound', priority: '300', port: '22', source_address_prefix: 'Internet'},{ name: 'Allow-HTTP', access: 'Allow', protocol: 'Tcp', direction: 'Inbound', priority: '100', port: '80', source_address_prefix: 'Internet'}]  
    include_tasks: ./confignetwork.yml

#  - name: Show NIC details
#    debug: 
#      var: NIC

  - name: Create a front-end virtual machines
    vars:
      myVM: myVM
      myTags: "Ansible=web"
    include: ./createvm.yml
  
  - name: Create back-end subnet and NSG rules
    vars:
      myVnetSubNet: myVnetSubNet-BE
      myPublicIP: myPublicIP-BE
      subnetAddPrefix:  "172.16.20.0/24"
      myNetworkSecurityGroup: myNSG-BE
      myNIC: myNIC-BE
      NSGlist: [{ name: 'Allow-SSH', access: 'Allow', protocol: 'Tcp', direction: 'Inbound', priority: '200', port: '22', source_address_prefix: 'Internet'},{ name: 'Allow-MySQL-FE', access: 'Allow', protocol: 'Tcp', direction: 'Inbound', priority: '100', port: '3306', source_address_prefix: '172.16.10.0/24'}, { name: 'Deny-internet-all', access: 'Deny', protocol: 'Tcp', direction: 'Outbound', priority: '300', port: '*', source_address_prefix: '*'}]  
    include_tasks: ./confignetwork.yml

#  - name: Show NIC details
#    debug: 
#      var: NIC

  - name: Create a back-end virtual machines
    vars:
      myVM: myVM-BE
      myTags: "Ansible=MySQL"
    include: ./createvm.yml