- hosts: localhost
  vars_files: 
    - vars/vars.yml
  roles:
    - ./modules
  gather_facts: no
    
  tasks:
# ----------------------------------------------------------------------------------
# Start with a resource group so that clean up is easy. This tasks is commented out
# since you cannot create resource group in this workshop.
# ----------------------------------------------------------------------------------
#  - name: Create a resource group
#    azure_rm_resourcegroup:
#      name: "{{ myResource_group }}"
#      location: eastus2
#
  - name: Create a virtual network. 
    azure_rm_virtualnetwork:
      resource_group: "{{ myResource_group }}"
      name: "{{ myVnet }}"
      address_prefixes: "172.16.0.0/16"

  - name: Create front-end subnet and NSG rules
    vars:
      subnetAddPrefix:  "{{ FE_subnetAddPrefix }}"
      NSGlist: "{{ FE_NSGlist }}"
    include_tasks: ./confignetwork.yml

#  - name: Show NIC details
#    debug: 
#      var: NIC

  - name: Create a front-end virtual machines
    vars:
      myVM: myVM
      myTags: "Ansible=web"
    include: ./createvm.yml
  
  - name: Create back-end subnet and NSG rules
    vars:
      myVnetSubNet: myVnetSubNet-BE
      myPublicIP: myPublicIP-BE
      subnetAddPrefix:  "{{ BE_subnetAddPrefix }}"
      myNetworkSecurityGroup: myNSG-BE
      myNIC: myNIC-BE
      NSGlist: "{{ BE_NSGlist }}"
    include_tasks: ./confignetwork.yml

#  - name: Show NIC details
#    debug: 
#      var: NIC

  - name: Create a back-end virtual machines
    vars:
      myVM: myVM-BE
      myTags: "Ansible=MySQL"
    include: ./createvm.yml