- hosts: localhost
  vars_files: 
    - ./vars.yml
    
  tasks:
# ----------------------------------------------------------------------------------
# Start with a resource group so that clean up is easy. This tasks is commented out
# since you cannot create resource group in this workshop.
# ----------------------------------------------------------------------------------
#  - name: Create a resource group
#    azure_rm_resourcegroup:
#      name: {{ myResource_group }}
#      location: eastus2
  - name: Create a virtual network. 
    azure_rm_virtualnetwork:
      resource_group: "{{ myResource_group }}"
      name: "{{ myVnet }}"
      address_prefixes: "172.16.0.0/16"

  - name: Create a subset within the virtual network
    azure_rm_subnet:
        resource_group: "{{ myResource_group }}"
        virtual_network_name: "{{ myVnet }}"
        name: "{{ myVnetSubNet }}"
        address_prefix_cidr:  "172.16.10.0/24"

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ myResource_group }}"
      allocation_method: Static
      name: "{{ myPublicIP }}"

  - name: Create Network Security Group and rules
    azure_rm_securitygroup:
      resource_group: "{{ myResource_group }}"
      name: "{{ myNetworkSecurityGroup}}"
      rules:
        - name: "{{ item.name }}"
          access: "{{ item.access }}"
          protocol: "{{ item.protocol }}"
          direction: "{{ item.direction }}"
          destination_port_range: "{{ item.port }}"
          priority: "{{ item.priority }}"
          source_address_prefix: "{{ item.source_address_prefix }}"
    loop: "{{ NSGlist }}"

  - name: Create virtual network interface card(NIC)
    azure_rm_networkinterface:
      resource_group: "{{ myResource_group }}"
      name: "{{ myNIC }}"
      virtual_network: "{{ myVnet }}"
      subnet: "{{ myVnetSubNet }}"
      ip_configurations:
        - name: ipconfig
          public_ip_address_name: "{{ myPublicIP }}"
      security_group: "{{ myNetworkSecurityGroup }}"
      
  - name: Create a virtual machines
    azure_rm_virtualmachine:
      resource_group: "{{ myResource_group }}"
      name: "{{ myVM }}"
      admin_username: "testadmin"
      admin_password: "Password1234!"
      vm_size: Standard_B1ms
      network_interfaces: "{{ myNIC }}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest
  