myResource_group: myResource_group
myVnet: myVnet
myVnetSubNet: "{{ myVnet }}Subnet"
myPublicIP: myPublicIP
myNetworkSecurityGroup: myNSG
myNIC: myNIC
myVM: myVM
NSGlist: 
  - name: Allow-SSH
    access: Allow
    protocol: Tcp
    direction: Inbound
    priority: 300
    port: 22 
    source_address_prefix: Internet
  - name: Allow-HTTP
    access: Allow
    protocol: Tcp
    direction: Inbound
    priority: 100
    port: 80
    source_address_prefix: Internet