- hosts: localhost
  vars:
    myResource_group: myResource_group
    myVnet: myVnet
    myVnetSubNet: "{{ myVnet }}Subnet"
    myPublicIP: myPublicIP
    myNetworkSecurityGroup: myNSG
    myNIC: myNIC
    myVM: myVM
    NSGlist: 
      - name: Allow-SSH
        access: Allow
        protocol: Tcp
        direction: Inbound
        priority: 300
        port: 22 
        source_address_prefix: Internet
      - name: Allow-HTTP
        access: Allow
        protocol: Tcp
        direction: Inbound
        priority: 100
        port: 80
        source_address_prefix: Internet 
    keyvault_name: mykeyvault
    secret_name: myVMSecret  
  roles:
    - ./modules

  tasks:
# ----------------------------------------------------------------------------------
# Start with a resource group so that clean up is easy. This tasks is commented out
# since you cannot create resource group in this workshop.
# ----------------------------------------------------------------------------------
#  - name: Create a resource group
#    azure_rm_resourcegroup:
#      name: {{ myResource_group }}
#      location: eastus2
  - name: Create a virtual network. 
    azure_rm_virtualnetwork:
      resource_group: "{{ myResource_group }}"
      name: "{{ myVnet }}"
      address_prefixes: "172.16.0.0/16"

  - name: Create a subset within the virtual network
    azure_rm_subnet:
        resource_group: "{{ myResource_group }}"
        virtual_network_name: "{{ myVnet }}"
        name: "{{ myVnetSubNet }}"
        address_prefix_cidr:  "172.16.10.0/24"

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ myResource_group }}"
      allocation_method: Static
      name: "{{ myPublicIP }}"

  - name: Create Network Security Group and rules
    azure_rm_securitygroup:
      resource_group: "{{ myResource_group }}"
      name: "{{ myNetworkSecurityGroup}}"
      rules:
        - name: "{{ item.name }}"
          access: "{{ item.access }}"
          protocol: "{{ item.protocol }}"
          direction: "{{ item.direction }}"
          destination_port_range: "{{ item.port }}"
          priority: "{{ item.priority }}"
          source_address_prefix: "{{ item.source_address_prefix }}"
    loop: "{{ NSGlist }}"

  - name: Create virtual network interface card(NIC)
    azure_rm_networkinterface:
      resource_group: "{{ myResource_group }}"
      name: "{{ myNIC }}"
      virtual_network: "{{ myVnet }}"
      subnet: "{{ myVnetSubNet }}"
      ip_configurations:
        - name: ipconfig
          public_ip_address_name: "{{ myPublicIP }}"
          primary: yes
      security_group: "{{ myNetworkSecurityGroup }}"

  - name: Get latest version of a secret
    azure_rm_keyvaultsecret_info:
      vault_uri: "https://{{ keyvault_name }}.vault.azure.net"
      name: "{{ secret_name }}"
    register: output

  - name: Create a virtual machines
    azure_rm_virtualmachine:
      resource_group: "{{ myResource_group }}"
      name: "{{ myVM }}"
      admin_username: "testadmin"
      admin_password: " {{ output['secrets'][0]['secret'] }}"
      vm_size: Standard_B1ms
      network_interfaces: "{{ myNIC }}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest
  
